# Copyright (c) 2022 The ZMK Contributors
# SPDX-License-Identifier: MIT

# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_LOG=y
# CONFIG_LOG_DEFAULT_LEVEL=4

CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_PERIPHERAL=y
CONFIG_ZMK_USB=n
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BATTERY=y
CONFIG_ZMK_EXT_POWER=y

CONFIG_INPUT=y
CONFIG_SPI=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y
CONFIG_PMW3610_ALT=y
CONFIG_PMW3610_ALT_SWAP_XY=n
CONFIG_PMW3610_ALT_INVERT_X=n
CONFIG_PMW3610_ALT_INVERT_Y=n

CONFIG_ZMK_DISPLAY=n
CONFIG_NICE_VIEW_WIDGET_STATUS=n
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y